version: '3'

services:
  lol_db:
    build: ./backend-db
    container_name: lol_db
    image: lol_db
    ports:
      - "5432:5432"
  lol_api:
    build: ./backend-api
    restart: always
    container_name: lol_api
    image: lol_api
    ports:
      - "80:80"
    environment:
      POSTGRES_HOST: lol_db
      POSTGRES_DB: lol_db 
      POSTGRES_PASSWORD: lol_admin
      POSTGRES_USER: postgres
      MAIL_ADDRESS: ${MAIL_ADDRESS}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
  lol_website:
    build: ./frontend/
    restart: always
    container_name: lol_website
    image: lol_website
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true